export default {
	getRandomErrorMessage() {
		const messages = [
			"Oops! Our system encountered an unexpected error. Please retry.",
			"Houston, we hit a technical glitch. Await your command to retry.",
			"A server misalignment occurred. Awaiting your re-initiation.",
			"Our data module experienced an anomaly. Awaiting your next move.",
			"Connection interference detected. Awaiting your command to proceed.",
			"Couldn't fetch the requested data. Ready for your next command.",
			"Technical disturbance detected. We're ready when you are to try again.",
			"System satellite lost sight of your data. Awaiting your retry.",
			"An internal error occurred. Please give the command to proceed.",
			"System synchronization error detected. We await your action.",
			"System anomaly detected. Please retry when ready.",
			"Transmission error occurred. Awaiting your instruction to rectify.",
			"Network disruption detected. We're on standby for your next move.",
			"Processing error encountered. Ready for your retry command.",
			"Your request was lost in transit. Awaiting re-initiation...",
			"System congestion detected. Ready for your next command.",
			"Technical fault encountered. Awaiting your signal to retry.",
			"Server-side disturbance detected. We're ready when you are.",
			"System response lag detected. Awaiting your retry command.",
			"Unexpected data variance occurred. Awaiting your next move.",
			"System stability compromised. Awaiting your command to fortify.",
			"Failed to retrieve server response. Ready for your retry signal.",
			"Communication breakdown detected. Awaiting your next command.",
			"Cosmic interference disrupted operations. Awaiting your retry.",
			"Your request was caught in a data vortex. Awaiting re-initiation...",
			"Validation error detected. Awaiting your next move.",
			"Temporal glitch detected. We're ready for your command.",
			"Network lag detected. Awaiting your instruction to proceed.",
			"Cache inconsistency detected. Awaiting your refresh command.",
			"A thread was torn in our data fabric. Ready for your mending command.",
			"Server faced a quantum entanglement. Awaiting your decoding instruction.",
			"System module malfunctioned. Awaiting your restart command.",
			"Mainframe disconnect detected. Awaiting your reconnection signal.",
			"Binary star interference detected. Awaiting your rectification command.",
			"Protocol mismatch found. Awaiting your command to adjust.",
			"Buffer overflow detected. Ready for your clearing command.",
			"Failed to establish a secure channel. Awaiting re-initiation.",
			"Gateway timeout occurred. Ready for your re-routing command.",
			"Database disconnect experienced. Awaiting your re-linking command.",
			"A cosmic ray skewed our computation. Awaiting recalibration.",
			"API response lost. We're on standby for your retrieval command.",
			"Unhandled exception detected. Awaiting your redirect command.",
			"Server horizon breach detected. Awaiting your reset command.",
			"Space-time data warp found. Ready for your stabilization command.",
			"Encountered a server singularity. Awaiting your evasion command.",
			"Technical inertia detected. Awaiting your acceleration command."
		];

		const randomIndex = Math.floor(Math.random() * messages.length);
		return messages[randomIndex];
	}
}
