import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import { IonContent, IonicVue, IonPage } from '@ionic/vue'
import log from '@/utils/log'
/* Core CSS required for Ionic components to work properly */
import '@ionic/vue/css/core.css'

/* Basic CSS for apps built with Ionic */
import '@ionic/vue/css/normalize.css'
import '@ionic/vue/css/structure.css'
import '@ionic/vue/css/typography.css'

/* Optional CSS utils that can be commented out */
import '@ionic/vue/css/padding.css'
import '@ionic/vue/css/float-elements.css'
import '@ionic/vue/css/text-alignment.css'
import '@ionic/vue/css/text-transformation.css'
import '@ionic/vue/css/flex-utils.css'
import '@ionic/vue/css/display.css'

/* Theme variables */
import './theme/variables.css'

import '@/assets/main.scss'
import VueMatomo from 'vue-matomo'

import NumberFormat from '@/plugins/NumberFormat.js'
import { createPinia } from 'pinia'
import Particles from 'vue3-particles'
import * as Sentry from '@sentry/vue'
import {
	ArcElement,
	BarElement,
	CategoryScale,
	Chart as ChartJS,
	DoughnutController,
	Filler,
	Legend,
	LinearScale,
	LineController,
	LineElement,
	LogarithmicScale,
	PieController,
	PointElement,
	Title,
	Tooltip
} from 'chart.js'
import RoundToTwo from '@/plugins/RoundToTwo.js'
import CopyToClipboard from '@/plugins/CopyToClipboard.js'
import useStore from '@/composables/useStore.js'

window.log = log

let pinia, app


createAppVue()

window.restartVueApp = () => {
	app.unmount()
	createAppVue()
}

function createAppVue() {
	pinia = createPinia()
	app = createApp(App)

	Sentry.init({
		app,
		dsn: 'https://9ac2652235044ecb84403bb1511a6e2b@sentry.finmars.com/7'
	})

	app.use(router).use(IonicVue).use(NumberFormat).use(RoundToTwo).use(CopyToClipboard).use(pinia).use(Particles)

	app.use(VueMatomo, {
		// Configure your matomo server and site by providing
		host: 'https://analytics.finmars.com',
		siteId: 1,

		// Changes the default .js and .php endpoint's filename
		// Default: 'matomo'
		trackerFileName: 'matomo',

		// Overrides the autogenerated tracker endpoint entirely
		// Default: undefined
		// trackerUrl: 'https://example.com/whatever/endpoint/you/have',

		// Overrides the autogenerated tracker script path entirely
		// Default: undefined
		// trackerScriptUrl: 'https://example.com/whatever/script/path/you/have',

		// Enables automatically registering pageviews on the router
		router: router,

		// Enables link tracking on regular links. Note that this won't
		// work for routing links (ie. internal Vue router links)
		// Default: true
		enableLinkTracking: true,

		// Require consent before sending tracking information to matomo
		// Default: false
		requireConsent: false,

		// Whether to track the initial page view
		// Default: true
		trackInitialView: false,

		// Run Matomo without cookies
		// Default: false
		disableCookies: true,

		// Require consent before creating matomo session cookie
		// Default: false
		requireCookieConsent: false,

		// Enable the heartbeat timer (https://developer.matomo.org/guides/tracking-javascript-guide#accurately-measure-the-time-spent-on-each-page)
		// Default: false
		enableHeartBeatTimer: true,

		// Set the heartbeat timer interval
		// Default: 15
		heartBeatTimerInterval: 15,

		// Whether or not to log debug information
		// Default: false
		debug: false,

		// UserID passed to Matomo (see https://developer.matomo.org/guides/tracking-javascript-guide#user-id)
		// Default: undefined
		userId: undefined,

		// Share the tracking cookie across subdomains (see https://developer.matomo.org/guides/tracking-javascript-guide#measuring-domains-andor-sub-domains)
		// Default: undefined, example '*.example.com'
		cookieDomain: undefined,

		// Tell Matomo the website domain so that clicks on these domains are not tracked as 'Outlinks'
		// Default: undefined, example: '*.example.com'
		domains: undefined,

		// A list of pre-initialization actions that run before matomo is loaded
		// Default: []
		// Example: [
		//   ['API_method_name', parameter_list],
		//   ['setCustomVariable','1','VisitorType','Member'],
		//   ['appendToTrackingUrl', 'new_visit=1'],
		//   etc.
		// ]
		preInitActions: [],

		// A function to determine whether to track an interaction as a site search
		// instead of as a page view. If not a function, all interactions will be
		// tracked as page views. Receives the new route as an argument, and
		// returns either an object of keyword, category (optional) and resultsCount
		// (optional) to track as a site search, or a falsey value to track as a page
		// view.
		// Default: false, i.e. track all interactions as page views
		// Example: (to) => {
		//   if (to.query.q && to.name === 'search') {
		//     return { keyword: to.query.q, category: to.params.category }
		//   } else {
		//    return null
		//   }
		// }
		trackSiteSearch: false,

		// Set this to include crossorigin attribute on the matomo script import
		// Default: undefined, possible values : 'anonymous', 'use-credentials'
		crossOrigin: undefined,
	});

	app.component('IonPage', IonPage).component('IonContent', IonContent)

	app.config.errorHandler = (err) => {
		console.error('Caught a global error', err)

		const store = useStore()

		store.setGlobalError(err)

		// You can navigate the user to a recovery page or log them out here
		// router.replace('/recovery');
	}

	app.mount('#app')
}

ChartJS.register(
	LineElement,
	PointElement,
	ArcElement,
	DoughnutController,
	LineController,
	PieController,
	CategoryScale,
	LinearScale,
	Filler,
	Legend,
	Tooltip,
	BarElement, Title,
	LogarithmicScale
)

// router.isReady().then(() => {})
